data_file: "data.csv"
localtime: "16:48:09.822"
output_file: "output.csv"
messages:
  - can_id: 107
    start_bit: 24
    bit_length: 12
    dlc: 8
    message: "Обороты двигателя"
    method: "LSB"
    scale: 3
    offset: 0